export type Language = 'en' | 'ko' | 'zh' | 'vi' | 'id';

export interface Question {
    id: string;
    text: Record<Language, string>;
    options: Record<Language, string[]>;
}

export interface SurveySet {
    id: 'market' | 'package';
    title: Record<Language, string>;
    questions: Question[];
}

export const SURVEY_DATA: Record<'market' | 'package', SurveySet> = {
    market: {
        id: 'market',
        title: {
            en: 'Market Validation',
            ko: '시장검증',
            zh: '市场验证',
            vi: 'Kiểm chứng thị trường',
            id: 'Validasi Pasar'
        },
        questions: [
            {
                id: 'q1',
                text: {
                    ko: '현재 TOPIK 공부를 하고 계신가요?',
                    en: 'Are you currently studying for TOPIK?',
                    zh: '你目前在学习TOPIK吗？',
                    vi: 'Bạn có đang học TOPIK không?',
                    id: 'Apakah Anda sedang belajar TOPIK?'
                },
                options: {
                    ko: ['적극적으로 준비 중이다', '가끔 공부한다', '생각은 있지만 시작하지 않았다', '전혀 계획 없다'],
                    en: ['Actively preparing', 'Studying occasionally', 'Thinking about it but haven\'t started', 'No plans at all'],
                    zh: ['正在积极准备', '偶尔学习', '有想法但还没开始', '完全没有计划'],
                    vi: ['Đang tích cực chuẩn bị', 'Thỉnh thoảng học', 'Có ý định nhưng chưa bắt đầu', 'Hoàn toàn không có kế hoạch'],
                    id: ['Sedang aktif mempersiapkan', 'Belajar sesekali', 'Sudah terpikir tapi belum mulai', 'Tidak ada rencana sama sekali']
                }
            },
            {
                id: 'q2',
                text: {
                    ko: '한국어능력시험(TOPIK)을 공부하는/하게된다면 주된 목적은 무엇인가요?',
                    en: 'What is your main purpose for studying TOPIK?',
                    zh: '学习TOPIK的主要目的是什么？',
                    vi: 'Mục đích chính của việc học TOPIK là gì?',
                    id: 'Apa tujuan utama Anda belajar TOPIK?'
                },
                options: {
                    ko: ['대학 입학', '취업 / 아르바이트', '비자 / 체류 목적', '개인 관심 / 취미'],
                    en: ['University admission', 'Employment / Part-time job', 'Visa / Stay purpose', 'Personal interest / Hobby'],
                    zh: ['大学入学', '就业/兼职', '签证/滞留目的', '个人兴趣/爱好'],
                    vi: ['Nhập học đại học', 'Việc làm / Làm thêm', 'Visa / Mục đích cư trú', 'Sở thích cá nhân'],
                    id: ['Masuk universitas', 'Pekerjaan / Kerja paruh waktu', 'Visa / Tujuan tinggal', 'Minat pribadi / Hobi']
                }
            },
            {
                id: 'q3',
                text: {
                    ko: '현재 사용하는 공부 방법은 무엇인가요?',
                    en: 'What is your current study method?',
                    zh: '你目前使用的学习方法是什么？',
                    vi: 'Phương pháp học tập hiện tại của bạn là gì?',
                    id: 'Apa metode belajar yang Anda gunakan saat ini?'
                },
                options: {
                    ko: ['학원 / 과외', '문제집', '유튜브 / 무료 콘텐츠', '별도로 하지 않음'],
                    en: ['Academy / Tutoring', 'Workbooks', 'YouTube / Free content', 'Not doing anything specific'],
                    zh: ['学院/家教', '习题集', 'YouTube/免费内容', '没有特别学习'],
                    vi: ['Trung tâm / Gia sư', 'Sách bài tập', 'YouTube / Nội dung miễn phí', 'Không làm gì cụ thể'],
                    id: ['Kursus / Privat', 'Buku latihan', 'YouTube / Konten gratis', 'Tidak melakukan apa pun secara khusus']
                }
            },
            {
                id: 'q4',
                text: {
                    ko: 'AI가 제출하고 한국어교사가 검토한 자료의 퀄리티는 어떨 것 같나요?',
                    en: 'What do you think about the quality of materials generated by AI and reviewed by Korean teachers?',
                    zh: '你认为AI生成并由韩国语教师审核的资料质量如何？',
                    vi: 'Bạn nghĩ gì về chất lượng tài liệu do AI tạo ra và giáo viên tiếng Hàn kiểm duyệt?',
                    id: 'Bagaimana menurut Anda kualitas materi yang dibuat oleh AI dan ditinjau oleh pengajar bahasa Korea?'
                },
                options: {
                    ko: ['실제 시험과 비슷하다', '연습하기 나쁘지 않다', '사용하고 싶지 않다', '모르겠다'],
                    en: ['Similar to the real exam', 'Not bad for practice', 'Don\'t want to use it', 'Don\'t know'],
                    zh: ['与实际考试相似', '练习还不错', '不想使用', '不知道'],
                    vi: ['Giống với kỳ thi thật', 'Không tệ để ôn tập', 'Không muốn sử dụng', 'Không biết'],
                    id: ['Mirip dengan ujian asli', 'Lumayan untuk latihan', 'Tidak ingin menggunakan', 'Tidak tahu']
                }
            },
            {
                id: 'q5',
                text: {
                    ko: '실제 시험과 같은 환경(IBT)으로 연습하는 것이 중요하다고 생각하시나요?',
                    en: 'Do you think it\'s important to practice in the same environment (IBT) as the real exam?',
                    zh: '你认为在与实际考试相同的环境（IBT）中练习重要吗？',
                    vi: 'Bạn có nghĩ việc luyện tập trong môi trường giống kỳ thi thật (IBT) là quan trọng không?',
                    id: 'Apakah Anda menganggap penting untuk berlatih di lingkungan yang sama (IBT) dengan ujian asli?'
                },
                options: {
                    ko: ['매우 중요하다', '어느 정도 중요하다', '별로 중요하지 않다', '전혀 중요하지 않다'],
                    en: ['Very important', 'Somewhat important', 'Not very important', 'Not important at all'],
                    zh: ['非常重要', '在一定程度上重要', '不太重要', '完全不重要'],
                    vi: ['Rất quan trọng', 'Quan trọng ở mức nào đó', 'Không quan trọng lắm', 'Hoàn toàn không quan trọng'],
                    id: ['Sangat penting', 'Cukup penting', 'Kurang penting', 'Sama sekali tidak penting']
                }
            },
            {
                id: 'q6',
                text: {
                    ko: '자신의 약한 부분만 집중적으로 연습할 수 있는 기능이 필요하다고 생각하시나요?',
                    en: 'Do you think a feature to practice only your weak areas intensively is necessary?',
                    zh: '你认为有必要集中练习自己薄弱环节的功能吗？',
                    vi: 'Bạn có nghĩ cần chức năng cho phép luyện tập tập trung vào những phần còn yếu không?',
                    id: 'Apakah Anda merasa fitur untuk berlatih bagian yang lemah secara intensif itu perlu?'
                },
                options: {
                    ko: ['매우 필요하다', '어느 정도 필요하다', '잘 모르겠다', '필요하지 않다'],
                    en: ['Very necessary', 'Somewhat necessary', 'Don\'t know', 'Not necessary'],
                    zh: ['非常必要', '在一定程度上必要', '不知道', '不需要'],
                    vi: ['Rất cần thiết', 'Cần thiết ở mức nào đó', 'Không biết', 'Không cần thiết'],
                    id: ['Sangat perlu', 'Cukup perlu', 'Tidak tahu', 'Tidak perlu']
                }
            },
            {
                id: 'q7',
                text: {
                    ko: '토픽 서비스가 있다면 아래 기능 중 가장 필요하다고 생각하는 것은 무엇인가요?',
                    en: 'If there were a TOPIK service, which of the following features would you need the most?',
                    zh: '如果有TOPIK服务，你认为最需要以下哪些功能？',
                    vi: 'Nếu có dịch vụ TOPIK, bạn nghĩ chức năng nào sau đây là cần thiết nhất?',
                    id: 'Jika ada layanan TOPIK, fitur mana yang menurut Anda paling dibutuhkan?'
                },
                options: {
                    ko: ['실제 시험 환경 모의시험', '약점 분석 리포트', '무제한 문제풀이', '별로 필요 없음'],
                    en: ['Mock exam in real environment', 'Weakness analysis report', 'Unlimited practice questions', 'Not really needed'],
                    zh: ['实际考试环境模拟考试', '薄弱环节分析报告', '无限解题', '不太需要'],
                    vi: ['Thi thử trong môi trường thật', 'Báo cáo phân tích điểm yếu', 'Giải bài tập không giới hạn', 'Không thực sự cần thiết'],
                    id: ['Ujian simulasi di lingkungan asli', 'Laporan analisis kelemahan', 'Latihan soal tanpa batas', 'Kurang perlu']
                }
            },
            {
                id: 'q8',
                text: {
                    ko: '월 3,000~5,000원 수준의 비용으로 TOPIK 연습 서비스를 이용할 의향이 있나요?',
                    en: 'Would you be willing to use a TOPIK practice service for 3,000-5,000 KRW per month?',
                    zh: '你愿意每月支付3,000-5,000韩元使用TOPIK练习服务吗？',
                    vi: 'Bạn có sẵn lòng sử dụng dịch vụ luyện tập TOPIK với mức giá khoảng 3.000~5.000 won mỗi tháng không?',
                    id: 'Apakah Anda bersedia menggunakan layanan latihan TOPIK dengan biaya 3.000~5.000 KRW per bulan?'
                },
                options: {
                    ko: ['있다', '조건에 따라 다르다', '잘 모르겠다', '없다'],
                    en: ['Yes', 'Depends on conditions', 'Don\'t know', 'No'],
                    zh: ['有', '视条件而定', '不知道', '没有'],
                    vi: ['Có', 'Tùy điều kiện', 'Không biết', 'Không'],
                    id: ['Ya', 'Tergantung kondisi', 'Tidak tahu', 'Tidak']
                }
            },
            {
                id: 'q9',
                text: {
                    ko: '이런 서비스가 있어도 사용하지 않을 이유는 무엇인가요?',
                    en: 'What would be the reason for not using such a service even if it were available?',
                    zh: '即使有这样的服务，不使用的原因是什么？',
                    vi: 'Lý do gì khiến bạn không sử dụng dịch vụ này ngay cả khi nó có sẵn?',
                    id: 'Apa alasan Anda tidak akan menggunakan layanan tersebut meskipun tersedia?'
                },
                options: {
                    ko: ['시간 부족', '현재 공부 방식으로 충분', '가격이 아깝다', '필요성을 못 느낌'],
                    en: ['Lack of time', 'Current study method is enough', 'Price is too high', 'Don\'t feel the need'],
                    zh: ['时间不足', '目前的学习方式已足够', '觉得价格可惜', '没感觉到必要性'],
                    vi: ['Thiếu thời gian', 'Phương pháp học hiện tại đã đủ', 'Tiếc tiền', 'Không cảm thấy cần thiết'],
                    id: ['Kurang waktu', 'Metode belajar saat ini sudah cukup', 'Harganya sayang', 'Merasa tidak butuh']
                }
            },
            {
                id: 'q10',
                text: {
                    ko: '이런 서비스를 사용한다면 응시하기 얼마 전 부터 사용할 것 같나요?',
                    en: 'If you were to use such a service, how long before the exam would you start?',
                    zh: '如果要使用这样的服务，考试前多久会开始使用？',
                    vi: 'Nếu sử dụng dịch vụ này, bạn nghĩ sẽ bắt đầu sử dụng từ bao giờ trước khi thi?',
                    id: 'Jika menggunakan layanan ini, kira-kira berapa lama sebelum ujian Anda akan mulai menggunakannya?'
                },
                options: {
                    ko: ['한 달 전', '6개월 전', '일주일 전', '한두 번'],
                    en: ['One month before', '6 months before', 'One week before', 'One or two times'],
                    zh: ['一个月前', '6个月前', '一周前', '一两次'],
                    vi: ['Một tháng trước', '6 tháng trước', 'Một tuần trước', 'Một hai lần'],
                    id: ['Satu bulan sebelumnya', '6 bulan sebelumnya', 'Satu minggu sebelumnya', 'Satu atau dua kali']
                }
            }
        ]
    },
    package: {
        id: 'package',
        title: {
            en: 'Package Design',
            ko: '패키지',
            zh: '套餐设计',
            vi: 'Gói dịch vụ',
            id: 'Paket Layanan'
        },
        questions: [
            {
                id: 'q1',
                text: {
                    ko: '실제 시험 환경과 다른 방식으로 연습하면서 어려움을 느낀 적이 있나요?',
                    en: 'Have you ever felt difficulty practicing in a way different from the real exam environment?',
                    zh: '在以与实际考试环境不同的方式练习时，你是否感到困难？',
                    vi: 'Bạn đã bao giờ gặp khó khăn khi luyện tập theo cách khác với môi trường thi thật chưa?',
                    id: 'Pernahkah Anda merasa kesulitan saat berlatih dengan cara yang berbeda dari lingkungan ujian asli?'
                },
                options: {
                    ko: ['매우 자주 있다', '가끔 있다', '거의 없다', '없다'],
                    en: ['Very often', 'Sometimes', 'Rarely', 'Never'],
                    zh: ['非常频繁', '有时', '几乎没有', '没有'],
                    vi: ['Rất thường xuyên', 'Thỉnh thoảng', 'Hầu như không', 'Không'],
                    id: ['Sangat sering', 'Kadang-kadang', 'Hampir tidak pernah', 'Tidak pernah']
                }
            },
            {
                id: 'q2',
                text: {
                    ko: '어디서나 시험과 동일한 환경(IBT)에서 연습할 수 있다면 도움이 될 것 같나요?',
                    en: 'Do you think it would be helpful if you could practice in the same environment (IBT) anywhere?',
                    zh: '如果你能在任何地方以与考试相同的环境（IBT）练习，你认为会有帮助吗？',
                    vi: 'Bạn có nghĩ sẽ hữu ích nếu có thể luyện tập trong môi trường giống kỳ thi thật (IBT) ở bất cứ đâu không?',
                    id: 'Apakah menurut Anda akan sangat membantu jika bisa berlatih di lingkungan yang sama (IBT) di mana saja?'
                },
                options: {
                    ko: ['매우 그렇다', '그렇다', '보통이다', '아니다'],
                    en: ['Very much so', 'Yes', 'Neutral', 'No'],
                    zh: ['非常是', '是', '一般', '不是'],
                    vi: ['Rất đúng', 'Đúng', 'Bình thường', 'Không'],
                    id: ['Sangat setuju', 'Setuju', 'Biasa saja', 'Tidak']
                }
            },
            {
                id: 'q3',
                text: {
                    ko: '자신의 약한 유형만 골라 반복 연습할 수 있다면 학습 효율이 높아질 것 같나요?',
                    en: 'Do you think study efficiency would increase if you could choose and practice only your weak question types?',
                    zh: '如果你能选择并反复练习自己薄弱的题型，你认为学习效率会提高吗？',
                    vi: 'Bạn có nghĩ hiệu quả học tập sẽ cao hơn nếu có thể chọn và luyện tập lặp lại chỉ những dạng bài còn yếu không?',
                    id: 'Apakah menurut Anda efisiensi belajar akan meningkat jika dapat memilih dan berlatih berulang kali tipe soal yang lemah saja?'
                },
                options: {
                    ko: ['매우 그렇다', '그렇다', '보통이다', '아니다'],
                    en: ['Very much so', 'Yes', 'Neutral', 'No'],
                    zh: ['非常是', '是', '一般', '不是'],
                    vi: ['Rất đúng', 'Đúng', 'Bình thường', 'Không'],
                    id: ['Sangat setuju', 'Setuju', 'Biasa saja', 'Tidak']
                }
            },
            {
                id: 'q4',
                text: {
                    ko: '본인의 취약점을 분석해주는 기능이 있다면 필요하다고 느끼시나요?',
                    en: 'Do you feel a feature that analyzes your weaknesses is necessary?',
                    zh: '你认为有必要分析自己薄弱环节的功能吗？',
                    vi: 'Bạn có cảm thấy cần chức năng phân tích điểm yếu của bản thân không?',
                    id: 'Apakah Anda merasa perlu fitur yang menganalisis kelemahan Anda?'
                },
                options: {
                    ko: ['매우 필요하다', '필요하다', '보통이다', '필요 없다'],
                    en: ['Very necessary', 'Necessary', 'Neutral', 'Not necessary'],
                    zh: ['非常必要', '必要', '一般', '不需要'],
                    vi: ['Rất cần thiết', 'Cần thiết', 'Bình thường', 'Không cần thiết'],
                    id: ['Sangat perlu', 'Perlu', 'Biasa saja', 'Tidak perlu']
                }
            },
            {
                id: 'q5',
                text: {
                    ko: '책을 사는 것보다 무제한으로 문제를 풀 수 있는 서비스가 더 효과적이라고 생각하시나요?',
                    en: 'Do you think a service that allows unlimited problem solving is more effective than buying workbooks?',
                    zh: '你认为可以无限解题的服务比买书更有效吗？',
                    vi: 'Bạn có nghĩ dịch vụ giải bài tập không giới hạn hiệu quả hơn việc mua sách không?',
                    id: 'Apakah Anda menganggap layanan yang memungkinkan latihan soal tanpa batas lebih efektif daripada membeli buku?'
                },
                options: {
                    ko: ['매우 그렇다', '그렇다', '보통이다', '아니다'],
                    en: ['Very much so', 'Yes', 'Neutral', 'No'],
                    zh: ['非常是', '是', '一般', '不是'],
                    vi: ['Rất đúng', 'Đúng', 'Bình thường', 'Không'],
                    id: ['Sangat setuju', 'Setuju', 'Biasa saja', 'Tidak']
                }
            },
            {
                id: 'q6',
                text: {
                    ko: '커피 한 잔 가격(월 3,000~5,000원)으로 이런 서비스를 이용할 수 있다면 부담 없이 사용할 수 있나요?',
                    en: 'If you could use this service for the price of a cup of coffee (3,000-5,000 KRW/month), would you use it without burden?',
                    zh: '如果可以以一杯咖啡的价格（每月3,000-5,000韩元）使用这样的服务，你会毫无负担地使用吗？',
                    vi: 'Nếu có thể sử dụng dịch vụ này với mức giá một ly cà phê (3.000~5.000 won/tháng), bạn có sẵn lòng dùng mà không thấy áp lực không?',
                    id: 'Jika dapat menggunakan layanan ini dengan harga secangkir kopi (3.000~5.000 KRW/bulan), apakah Anda dapat menggunakannya tanpa beban?'
                },
                options: {
                    ko: ['매우 그렇다', '그렇다', '보통이다', '아니다'],
                    en: ['Very much so', 'Yes', 'Neutral', 'No'],
                    zh: ['非常是', '是', '一般', '不是'],
                    vi: ['Rất đúng', 'Đúng', 'Bình thường', 'Không'],
                    id: ['Sangat setuju', 'Setuju', 'Biasa saja', 'Tidak']
                }
            },
            {
                id: 'q7',
                text: {
                    ko: 'IBT 모의시험 + 약점 분석 + 무제한 문제풀이 기능이 모두 포함된 서비스가 있다면 사용 의향이 있나요?',
                    en: 'Would you be willing to use a service that includes IBT mock exams, weakness analysis, and unlimited problem solving?',
                    zh: '如果有包含IBT模拟考试+薄弱环节分析+无限解题功能的服务，你愿意使用吗？',
                    vi: 'Nếu có dịch vụ bao gồm tất cả các chức năng: Thi thử IBT + Phân tích điểm yếu + Giải bài tập không giới hạn, bạn có ý định sử dụng không?',
                    id: 'Apakah Anda bersedia menggunakan layanan yang mencakup simulasi ujian IBT + analisis kelemahan + latihan soal tanpa batas?'
                },
                options: {
                    ko: ['바로 사용하고 싶다', '사용해보고 싶다', '고민해볼 것 같다', '사용하지 않을 것 같다'],
                    en: ['Want to use immediately', 'Want to try it', 'Might consider it', 'Unlikely to use'],
                    zh: ['想立即使用', '想试用', '可能会考虑', '似乎不会使用'],
                    vi: ['Muốn sử dụng ngay', 'Muốn dùng thử', 'Sẽ cân nhắc', 'Chắc là không dùng'],
                    id: ['Ingin segera menggunakan', 'Ingin mencoba', 'Sepertinya akan mempertimbangkan', 'Sepertinya tidak akan menggunakan']
                }
            },
            {
                id: 'q8',
                text: {
                    ko: '이런 서비스가 있다면 TOPIK 점수 향상에 도움이 될 것 같나요?',
                    en: 'Do you think such a service would help improve your TOPIK scores?',
                    zh: '如果有这样的服务，你认为会有助于提高TOPIK分数吗？',
                    vi: 'Nếu có dịch vụ này, bạn có nghĩ nó sẽ giúp cải thiện điểm TOPIK không?',
                    id: 'Apakah menurut Anda layanan semacam itu akan membantu meningkatkan skor TOPIK Anda?'
                },
                options: {
                    ko: ['매우 그렇다', '그렇다', '보통이다', '아니다'],
                    en: ['Very much so', 'Yes', 'Neutral', 'No'],
                    zh: ['非常是', '是', '一般', '不是'],
                    vi: ['Rất đúng', 'Đúng', 'Bình thường', 'Không'],
                    id: ['Sangat setuju', 'Setuju', 'Biasa saja', 'Tidak']
                }
            },
            {
                id: 'q9',
                text: {
                    ko: '위 조건을 고려했을 때, 해당 서비스가 필요하다고 생각하시나요?',
                    en: 'Considering the above conditions, do you think this service is necessary?',
                    zh: '考虑到以上条件，你认为该服务必要吗？',
                    vi: 'Cân nhắc các điều kiện trên, bạn có nghĩ dịch vụ này là cần thiết không?',
                    id: 'Mempertimbangkan kondisi di atas, apakah menurut Anda layanan tersebut perlu?'
                },
                options: {
                    ko: ['매우 필요하다', '필요하다', '보통이다', '필요 없다'],
                    en: ['Very necessary', 'Necessary', 'Neutral', 'Not necessary'],
                    zh: ['非常必要', '必要', '一般', '不需要'],
                    vi: ['Rất cần thiết', 'Cần thiết', 'Bình thường', 'Không cần thiết'],
                    id: ['Sangat perlu', 'Perlu', 'Biasa saja', 'Tidak perlu']
                }
            },
            {
                id: 'q10',
                text: {
                    ko: '모바일로 틈틈이 학습하는 것이 효과적이라고 생각하시나요?',
                    en: 'Do you think studying occasionally on mobile is effective?',
                    zh: '你认为利用业余时间在手机上学习有效吗？',
                    vi: 'Bạn có nghĩ việc học tranh thủ trên điện thoại là hiệu quả không?',
                    id: 'Apakah Anda menganggap belajar di waktu luang melalui ponsel itu efektif?'
                },
                options: {
                    ko: ['매우 그렇다', '그렇다', '보통이다', '아니다'],
                    en: ['Very much so', 'Yes', 'Neutral', 'No'],
                    zh: ['非常是', '是', '一般', '辨别力'],
                    vi: ['Rất đúng', 'Đúng', 'Bình thường', 'Không'],
                    id: ['Sangat setuju', 'Setuju', 'Biasa saja', 'Tidak']
                }
            }
        ]
    }
};

export const UI_STRINGS: Record<Language, any> = {
    ko: {
        selectLanguage: 'Select Language',
        next: '다음',
        start: '시작하기',
        thankYou: '감사합니다!',
        phoneRequest: '번호를 남겨주시면 추첨을 통해 올리브영 쿠폰을 드립니다. 감사합니다!',
        submit: '제출하기',
        adminTitle: '설문 결과',
        back: '뒤로',
        loading: '로딩 중...',
        phonePlaceholder: '010-0000-0000',
    },
    en: {
        selectLanguage: 'Select Language',
        next: 'Next',
        start: 'Start',
        thankYou: 'Thank You!',
        phoneRequest: 'Leave your phone number for a chance to win an Olive Young coupon! Thank you.',
        submit: 'Submit',
        adminTitle: 'Survey Results',
        back: 'Back',
        loading: 'Loading...',
        phonePlaceholder: 'Phone Number',
    },
    zh: {
        selectLanguage: '选择语言',
        next: '下一步',
        start: '开始',
        thankYou: '谢谢！',
        phoneRequest: '留下您的电话号码，就有机会获得Olive Young优惠券！谢谢。',
        submit: '提交',
        adminTitle: '调查结果',
        back: '返回',
        loading: '加载中...',
        phonePlaceholder: '电话号码',
    },
    vi: {
        selectLanguage: 'Chọn ngôn ngữ',
        next: 'Tiếp theo',
        start: 'Bắt đầu',
        thankYou: 'Cảm ơn!',
        phoneRequest: 'Để lại số điện thoại để có cơ hội nhận coupon Olive Young! Cảm ơn.',
        submit: 'Gửi',
        adminTitle: 'Kết quả khảo sát',
        back: 'Quay lại',
        loading: 'Đang tải...',
        phonePlaceholder: 'Số điện thoại',
    },
    id: {
        selectLanguage: 'Pilih Bahasa',
        next: 'Berikutnya',
        start: 'Mulai',
        thankYou: 'Terima Kasih!',
        phoneRequest: 'Tinggalkan nomor telepon Anda untuk kesempatan memenangkan kupon Olive Young! Terima kasih.',
        submit: 'Kirim',
        adminTitle: 'Hasil Survei',
        back: 'Kembali',
        loading: 'Memuat...',
        phonePlaceholder: 'Nomor Telepon',
    }
};
